### ISSUE TITLE
there's no sql file

### ISSUE THREAD

**Issue by iheind** [arvatross/jobs4you#1]
hi, how to install database?

**Comment by avdajay** [comment]
Hello, thank you for your interest in this repo. Be reminded that I wouldn't be supporting this anymore for code changes, but I have added the SQL file to the database folder. Kindly refer to commit #e8ee275. Just upload the SQL file to your database, and reconfigure the database configuration settings on config/db.php. To create an admin account, create an account through the sign-up page and change the account's role id on the database user table. This system doesn't have the "setup" to create an account or configure settings.

**Comment by iheind** [comment]
hi thank you for response and greet job.
but, your sql is empty

**Comment by avdajay** [comment]
Hello,

The SQL file included is the structure only, with no default contents. You can try using the system and add those data. Some of the data, for example, the locations, need to be added through the database manually.

**Comment by iheind** [comment]
@avdajay hi my friend, please check again your commit #e8ee275 is empty structure.

`-- Data exporting was unselected.`

**Comment by avdajay** [comment]
Sorry, can you try it again?

**Comment by iheind** [comment]
hi thank you. how to set base url? because, template not load.
i test on my local. http://localhost/job4you

**Comment by avdajay** [comment]
I have set a virtual host such as http://job4you.test. You can set-up your own virtual host on your computer or edit the functions.php file in the main project folder, then scroll down to a function called "asset" and append /job4you/ at the front of the path. I would recommend setting up a virtual host to avoid file path errors in the future.

**Comment by avdajay** [comment]
Closing this because of no reply/update.
