### ISSUE TITLE
 MySQL said: #1824 - Failed to open the referenced table 'locations'

### ISSUE THREAD

**Issue by ghost** [arvatross/jobs4you#2]
Dear Vincent,
I know you are no longer developing this system. but I would like to try and use it. I ran into the following error:

```-- Dumping structure for table jobwander.applicants
CREATE TABLE IF NOT EXISTS `applicants` (
  `name` varchar(255) DEFAULT NULL,
  `address` text,
  `phone` varchar(255) DEFAULT NULL,
  `summary` text,
  `facebook` varchar(255) DEFAULT NULL,
  `twitter` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `location` tinyint(4) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `location` (`location`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `fk_applicants_locations` FOREIGN KEY (`location`) REFERENCES `locations` (`id`),
  CONSTRAINT `fk_applicants_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

 MySQL said: #1824 - Failed to open the referenced table 'locations'

![error_0](https://user-images.githubusercontent.com/842504/117792030-3667dd80-b24b-11eb-9370-29ad88819dff.png)

Please help me to solve this problem.

Regards,
The Lacesz

**Comment by avdajay** [comment]
Hey, there. Either the "locations" table wasn't created or created earlier than the "applicants" table. Solutions will be to remove the references and them later or migrate the locations table first before applicants. I would create a locations table first manually and then import the SQL file if that helps. I have already forgotten, but can you see a timestamp that indicates whichever gets migrated first?

**Comment by avdajay** [comment]
Closing this because of no reply/update.
